---
- name: Ensure Old Docker Instances Absent
  become: yes
  apt:
      name: "{{ item }}"
      state: absent
  with_items:
      - "docker"
      - "docker-engine"
      - "docker.io"

- name: Ensure Docker Offical GPG Key
  become: yes
  apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

- name: Ensure Edge Docker Repository
  become: yes
  apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
      state: present
      update_cache: yes

- name: Ensure Docker
  become: yes
  apt:
      name: "{{ item }}"
      state: present
  with_items:
      - linux-image-extra-{{ ansible_kernel }}
      - linux-image-extra-virtual
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - docker-ce

- name: Ensure User in Docker Group
  become: yes
  user:
      name: ubuntu
      append: yes
      groups:
          - docker
      state: present
